Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,6 +13,22 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Set k8s directory based on REPLICA_MODE
+      id: set-dirr
+      run: |
+        if [ "$REPLICA_MODE" == "0" ]; then
+          echo "K8S_DIR=k8s/low" >> $GITHUB_ENV
+        elif [ "$REPLICA_MODE" == "1" ]; then
+          echo "K8S_DIR=k8s/medium" >> $GITHUB_ENV
+        elif [ "$REPLICA_MODE" == "2" ]; then
+          echo "K8S_DIR=k8s/high" >> $GITHUB_ENV
+        else
+          echo "Invalid REPLICA_MODE value. Must be 0, 1, or 2."
+          exit 1
+        fi
+      env:
+        REPLICA_MODE: ${{ vars.REPLICA_MODE }}  # Access repository variable
+
     - name: Print K8S_DIR
       run: echo "K8S_DIR is $K8S_DIR"
       env:
