fix ci/cd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -63,6 +63,20 @@ jobs:
     
     - name: install gke auth plugin
       run: gcloud components install gke-gcloud-auth-plugin
+
+    - name: Set k8s directory based on REPLICA_MODE
+      id: set-dir
+      run: |
+        if [ "${{ env.REPLICA_MODE }}" == "0" ]; then
+          echo "K8S_DIR=k8s/low" >> $GITHUB_ENV
+        elif [ "${{ env.REPLICA_MODE }}" == "1" ]; then
+          echo "K8S_DIR=k8s/medium" >> $GITHUB_ENV
+        elif [ "${{ env.REPLICA_MODE }}" == "2" ]; then
+          echo "K8S_DIR=k8s/high" >> $GITHUB_ENV
+        else
+          echo "Invalid REPLICA_MODE value. Must be 0, 1, or 2."
+          exit 1
+        fi
       
     - name: run sh
-      run: ./create_services.sh
+      run: ./create_services_cicd.sh
